# Generated by Django 4.2.1 on 2023-05-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('phone', models.CharField(max_length=250, verbose_name='phone')),
                ('peopleAmount', models.IntegerField(verbose_name='amount of people')),
            ],
        ),
    ]
