# Generated by Django 4.2.1 on 2023-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursions',
            options={'ordering': ['date'], 'verbose_name': 'Excursion', 'verbose_name_plural': 'Excursions'},
        ),
        migrations.AddField(
            model_name='excursions',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='name'),
        ),
    ]
