# Generated by Django 4.2.1 on 2023-06-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_account_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='guide',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zoo.account'),
        ),
        migrations.AddField(
            model_name='excursions',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
