# Generated by Django 4.2.1 on 2023-06-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_alter_excursions_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zoo.account'),
        ),
    ]
